Update Chinese
fishpondstudio/IndustryIdle-i18n pull request #35
Opened 2021-04-16 23:00 UTC by Orange23333

# To Aministrator

_Because I can't connect to Discord, so I leave some messages here._

 **It is suggested to change the file name to `zh-CN.ts`, and change the name of the dictionary form `ZH` to `ZH_CN`.** 

 **I use the converter to make a simple conversion from `simplified Chinese` to `traditional Chinese`. This will help people who are used to using traditional Chinese to read texts. Further localization may be needed.** 

# 修改。

1. Fashion: `塑造` -> `时装`
2. LumberMill: `伐木工坊` -> `锯木厂`
3. 个人建议: `发电`+站/厂 `矿`+场
4. `生产`，`数量`等用词
5. `建造`等用词
6. `...怎样的` -> `怎样的...`
7. 移除部分_空格_。
8. 修正部分根据实际游戏意译的内容
9. （略）

----------

# 留言

_撞车了（虽然是必然的事），今天更新发现已经被翻译好了，也好我估计我得翻译个把个星期才能出来。那我就稍微提出一点点意见好了(=▽=)_

_虽然不是很喜欢`zh-TW`这种说法（`zh-SP`和`zh-TD`更好一些），但这是难改变的标准。_

2021-04-17 04:09 UTC, Orange23333 commented
@LazySu @snewpeap

2021-04-17 04:09 UTC, Orange23333 commented
@LazySu @snewpeap 请检查谢谢！

2021-04-17 04:12 UTC, Orange23333 commented
@LazySu @snewpeap 看看

2021-04-17 05:17 UTC, snewpeap requested changes
社区感谢你。在下有一些建议，后附。
The community thank you. There are some suggestions below, attached.

2021-04-17 05:17 UTC, snewpeap commented on zh_CN.ts
> +    MovingAverageDesc: "显示资源变化的平均值，而不是实时变化量",
moving average好像是个专有名词（[百度百科](https://baike.baidu.com/item/滑动平均/2640979)|[Wikipedia](https://zh.wikipedia.org/wiki/%E7%A7%BB%E5%8B%95%E5%B9%B3%E5%9D%87)），考虑到原文是"Show moving average of change"，建议如下：
Moving average seems to be a term. Considering that the original text is "Show moving average of change", the suggestions are as follows:
```suggestion
    MovingAverage: "移动平均",
    MovingAverageDesc: "显示资源变化的移动平均值，而不是实时变化量",
```

2021-04-17 05:17 UTC, snewpeap commented on zh_CN.ts
>      HighlightNotMakingProfit: "...不盈利的",
你忘了这个
You forgot this
```suggestion
    HighlightNotMakingProfit: "不盈利的...",
```

2021-04-17 05:17 UTC, snewpeap commented on zh_CN.ts
>      LoggingCamp2xOutput: "Deforestation",
你忘了这个
You forgot this
```suggestion
    LoggingCamp2xOutput: "毁林",
```

2021-04-17 05:17 UTC, snewpeap commented on zh_CN.ts
> +    LoggingCamp2xOutputDesc: "伐木场产生2倍的铁，但运输木头消耗2倍的燃料",
应该是“2倍的木头”不是“铁”
Should be "2x wood" not "iron"
```suggestion
    LoggingCamp2xOutputDesc: "伐木场产生2倍的木头，但运输木头消耗2倍的燃料",
```

2021-04-17 05:44 UTC, snewpeap commented
还有一些重要但尚未保持一致的名词翻译，列举如下：
There are still some important but not yet consistently translated nouns, as listed below:
- tile -> 瓷砖，地砖，格；
- policy -> 策略，政策；
- capacity -> 产能，能力，容量；
- etc.
我不知道统一到哪个翻译更好，大伙可以给给建议。
I don't know which translation to unify to. Need suggestions.

2021-04-17 16:28 UTC, insraq commented
@snewpeap @Orange23333 Wow, thanks for your contribution and review! I have merged all the changes and feel free to make further corrections.

2021-04-17 16:28 UTC, merged

2021-04-18 05:30 UTC, Orange23333 commented
> 社区感谢你。在下有一些建议，后附。
> The community thank you. There are some suggestions below, attached.
谢谢！

2021-04-18 05:30 UTC, Orange23333 commented
谢谢指正与建议！